### ISSUE TITLE
First test

### ISSUE THREAD

**Issue by petercorke** [CallumJHays/mvt-phonesensor-app#1]
Web browser tells me
```
Failed to open a WebSocket connection.
See server log for more information.
```
Python program says
```
Error in opening handshake
Traceback (most recent call last):
  File "/Users/corkep/opt/miniconda3/lib/python3.8/site-packages/websockets/server.py", line 130, in handler
    path = await self.handshake(
  File "/Users/corkep/opt/miniconda3/lib/python3.8/site-packages/websockets/server.py", line 532, in handshake
    early_response = await early_response_awaitable
  File "/Users/corkep/opt/miniconda3/lib/python3.8/site-packages/websockets/server.py", line 313, in process_request
    return await response
  File "/Users/corkep/Dropbox/code/mvt-phonesensor-app/PhoneSensor/phone_sensor.py", line 161, in _maybe_serve_static
    }, file.read_bytes())
  File "/Users/corkep/opt/miniconda3/lib/python3.8/pathlib.py", line 1225, in read_bytes
    with self.open(mode='rb') as f:
  File "/Users/corkep/opt/miniconda3/lib/python3.8/pathlib.py", line 1218, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/Users/corkep/opt/miniconda3/lib/python3.8/pathlib.py", line 1074, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/corkep/Dropbox/code/mvt-phonesensor-app/PhoneSensor/../build/index.html'

```

not sure what folder it's looking for above the root folder, but nothing called `build`.

The python program sent me to port 8765, your instructions and npm install sent me to 3000.

And yes, had all the certificate hassle...

**Comment by CallumJHays** [comment]
Ah yes, so far I've hard-coded the app in dev mode as if I was on my home network. The trouble line is:

// src/api.ts
static WS_URL = "wss://192.168.0.239:8765/ws";



Since I'm now proxying the npm dev-server via the python server this hard-coding of the address shouldn't be necessary, and can be replaced with the currently commented version of that line (above it). You must also also set DEV_MODE to True in PhoneSensor.py to enable this proxy functionality

As for the "build" dir, that gets built with npm run build which I will eventually automate with a GitHub workflow.yml. Depending on how this ends up being distributed with machinevisiontoolbox we could either commit the build to master or include it in the setup.py install.

**Comment by CallumJHays** [comment]
The project is now pip-installable from pypi as well as github. See the current `README.md`. Additionally, there is now a `proxy_client_from` argument in the constructor which can be used to run tests alongside the webpack development server.
